# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20180625140758) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "batter_scoutings", force: :cascade do |t|
    t.bigint "team_id"
    t.bigint "player_id"
    t.bigint "season_id"
    t.integer "PA"
    t.float "FA"
    t.float "FC"
    t.float "FS"
    t.float "SI"
    t.float "CH"
    t.float "SL"
    t.float "CU"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["player_id"], name: "index_batter_scoutings_on_player_id"
    t.index ["season_id"], name: "index_batter_scoutings_on_season_id"
    t.index ["team_id"], name: "index_batter_scoutings_on_team_id"
  end

  create_table "batter_stats", force: :cascade do |t|
    t.bigint "batter_id"
    t.string "handedness"
    t.string "range"
    t.integer "woba", default: 0
    t.string "ops", default: "0"
    t.integer "ab", default: 0
    t.integer "so", default: 0
    t.integer "bb", default: 0
    t.integer "sb", default: 0
    t.float "fb", default: 0.0
    t.float "gb", default: 0.0
    t.float "ld", default: 0.0
    t.integer "wrc", default: 0
    t.integer "obp", default: 0
    t.integer "slg", default: 0
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["batter_id"], name: "index_batter_stats_on_batter_id"
  end

  create_table "batters", force: :cascade do |t|
    t.bigint "team_id"
    t.bigint "game_id"
    t.bigint "player_id"
    t.bigint "season_id"
    t.boolean "starter"
    t.integer "lineup"
    t.string "position"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["game_id"], name: "index_batters_on_game_id"
    t.index ["player_id"], name: "index_batters_on_player_id"
    t.index ["season_id"], name: "index_batters_on_season_id"
    t.index ["team_id"], name: "index_batters_on_team_id"
  end

  create_table "game_days", force: :cascade do |t|
    t.bigint "season_id"
    t.date "date"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["season_id"], name: "index_game_days_on_season_id"
  end

  create_table "game_stats", force: :cascade do |t|
    t.bigint "game_id"
    t.integer "row_number"
    t.integer "home_score"
    t.integer "away_score"
    t.integer "hits"
    t.integer "home_runs"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["game_id"], name: "index_game_stats_on_game_id"
  end

  create_table "gameresults", force: :cascade do |t|
    t.string "day"
    t.string "month"
    t.string "year"
    t.string "time"
    t.string "away_team"
    t.string "home_team"
    t.string "away_ml"
    t.string "home_ml"
    t.string "away_total"
    t.string "home_total"
    t.string "first_temp"
    t.string "second_temp"
    t.string "third_temp"
    t.string "first_dp"
    t.string "second_dp"
    t.string "third_dp"
    t.string "first_humid"
    t.string "second_humid"
    t.string "third_humid"
    t.string "first_baro"
    t.string "second_baro"
    t.string "third_baro"
    t.string "first_wind_direction"
    t.string "second_wind_direction"
    t.string "third_wind_direction"
    t.string "first_wind_speed"
    t.string "second_wind_speed"
    t.string "third_wind_speed"
    t.string "away_score_first"
    t.string "away_score_second"
    t.string "away_score_third"
    t.string "away_score_forth"
    t.string "away_score_fifth"
    t.string "away_score_sixth"
    t.string "away_score_seventh"
    t.string "away_score_eighth"
    t.string "away_score_nineth"
    t.string "away_score_tenth"
    t.string "home_score_first"
    t.string "home_score_second"
    t.string "home_score_third"
    t.string "home_score_forth"
    t.string "home_score_fifth"
    t.string "home_score_sixth"
    t.string "home_score_seventh"
    t.string "home_score_eighth"
    t.string "home_score_nineth"
    t.string "home_score_tenth"
    t.string "total_hits_both_team"
    t.string "total_walks_both_team"
    t.string "total_doubles_both_team"
    t.string "total_triples_both_team"
    t.string "total_bases_both_team"
    t.string "away_starter_last_game"
    t.string "away_starter_first_name"
    t.string "away_starter_handedness"
    t.string "home_starter_last_name"
    t.string "home_starter_first_name"
    t.string "home_starter_handedness"
    t.string "filtered_average_one"
    t.string "filtered_average_two"
    t.string "game_id"
    t.string "game_date"
    t.string "home_abbr"
    t.string "away_abbr"
    t.string "stadium"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "games", force: :cascade do |t|
    t.bigint "game_day_id"
    t.bigint "away_team_id"
    t.bigint "home_team_id"
    t.string "away_money_line"
    t.string "home_money_line"
    t.string "away_total"
    t.string "home_total"
    t.integer "game_id"
    t.string "game_date"
    t.string "ump"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["away_team_id"], name: "index_games_on_away_team_id"
    t.index ["game_day_id"], name: "index_games_on_game_day_id"
    t.index ["home_team_id"], name: "index_games_on_home_team_id"
  end

  create_table "lancers", force: :cascade do |t|
    t.bigint "team_id"
    t.bigint "game_id"
    t.bigint "player_id"
    t.bigint "season_id"
    t.boolean "starter"
    t.boolean "bullpen"
    t.integer "pitches"
    t.float "ip"
    t.integer "bb"
    t.integer "h"
    t.integer "r"
    t.integer "np"
    t.integer "s"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["game_id"], name: "index_lancers_on_game_id"
    t.index ["player_id"], name: "index_lancers_on_player_id"
    t.index ["season_id"], name: "index_lancers_on_season_id"
    t.index ["team_id"], name: "index_lancers_on_team_id"
  end

  create_table "pitcher_scoutings", force: :cascade do |t|
    t.bigint "team_id"
    t.bigint "player_id"
    t.bigint "season_id"
    t.float "IP"
    t.float "FA"
    t.float "FC"
    t.float "FS"
    t.float "SI"
    t.float "CH"
    t.float "SL"
    t.float "CU"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["player_id"], name: "index_pitcher_scoutings_on_player_id"
    t.index ["season_id"], name: "index_pitcher_scoutings_on_season_id"
    t.index ["team_id"], name: "index_pitcher_scoutings_on_team_id"
  end

  create_table "pitcher_stats", force: :cascade do |t|
    t.bigint "lancer_id"
    t.string "handedness"
    t.string "range"
    t.float "whip", default: 0.0
    t.float "ip", default: 0.0
    t.integer "so", default: 0
    t.integer "bb", default: 0
    t.integer "fip", default: 0
    t.float "xfip", default: 0.0
    t.float "kbb", default: 0.0
    t.integer "woba", default: 0
    t.string "ops", default: "0"
    t.float "era", default: 0.0
    t.float "fb", default: 0.0
    t.float "gb", default: 0.0
    t.float "ld", default: 0.0
    t.integer "h", default: 0
    t.float "siera", default: 0.0
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["lancer_id"], name: "index_pitcher_stats_on_lancer_id"
  end

  create_table "player_scouts", force: :cascade do |t|
    t.bigint "player_id"
    t.string "relies"
    t.string "description"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["player_id"], name: "index_player_scouts_on_player_id"
  end

  create_table "players", force: :cascade do |t|
    t.bigint "team_id"
    t.string "name"
    t.string "identity"
    t.string "fangraph_id"
    t.string "bathand"
    t.string "throwhand"
    t.integer "age"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "mlb_id"
    t.index ["team_id"], name: "index_players_on_team_id"
  end

  create_table "prevgames", force: :cascade do |t|
    t.integer "day"
    t.string "month"
    t.integer "year"
    t.string "time"
    t.string "away_team"
    t.string "home_team"
    t.integer "away_ml"
    t.integer "home_ml"
    t.string "away_total"
    t.string "home_total"
    t.float "TEMP"
    t.float "DP"
    t.integer "humid"
    t.float "BARO"
    t.string "wind"
    t.string "speed"
    t.integer "a1"
    t.integer "a2"
    t.integer "a3"
    t.integer "a4"
    t.integer "h1"
    t.integer "h2"
    t.integer "h3"
    t.integer "h4"
    t.float "away"
    t.float "home"
    t.float "total"
    t.integer "total_home_runs_both_team"
    t.integer "total_hits_both_team"
    t.string "away_starter_last_game"
    t.string "away_starter_first_name"
    t.string "away_starter_handedness"
    t.float "away_pitcher_game_first_blue"
    t.float "away_pitcher_game_opp_first_blue"
    t.float "away_difference"
    t.float "away_pitcher_game_second_blue"
    t.float "away_pitcher_game_opp_second_blue"
    t.string "home_starter_last_name"
    t.string "home_starter_first_name"
    t.string "home_starter_handedness"
    t.float "home_pitcher_game_first_blue"
    t.float "home_pitcher_game_opp_first_blue"
    t.float "home_difference"
    t.float "home_pitcher_game_second_blue"
    t.float "home_pitcher_game_opp_second_blue"
    t.float "total_line"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "Home_Team"
    t.float "N"
    t.string "M"
    t.integer "total_walks_both_team"
  end

  create_table "results", force: :cascade do |t|
    t.string "day"
    t.string "month"
    t.string "year"
    t.string "time"
    t.string "away_team"
    t.string "home_team"
    t.string "away_ml"
    t.string "home_ml"
    t.string "away_total"
    t.string "home_total"
    t.string "first_temp"
    t.string "second_temp"
    t.string "third_temp"
    t.string "first_dp"
    t.string "second_dp"
    t.string "third_dp"
    t.string "first_humid"
    t.string "second_humid"
    t.string "third_humid"
    t.string "first_baro"
    t.string "second_baro"
    t.string "third_baro"
    t.string "first_wind_direction"
    t.string "second_wind_direction"
    t.string "third_wind_direction"
    t.string "first_wind_speed"
    t.string "second_wind_speed"
    t.string "third_wind_speed"
    t.string "away_score_first"
    t.string "away_score_second"
    t.string "away_score_third"
    t.string "away_score_forth"
    t.string "away_score_fifth"
    t.string "away_score_sixth"
    t.string "away_score_seventh"
    t.string "away_score_eighth"
    t.string "away_score_nineth"
    t.string "away_score_tenth"
    t.string "home_score_first"
    t.string "home_score_second"
    t.string "home_score_third"
    t.string "home_score_forth"
    t.string "home_score_fifth"
    t.string "home_score_sixth"
    t.string "home_score_seventh"
    t.string "home_score_eighth"
    t.string "home_score_nineth"
    t.string "home_score_tenth"
    t.string "total_hits_both_team"
    t.string "total_walks_both_team"
    t.string "total_doubles_both_team"
    t.string "total_triples_both_team"
    t.string "total_bases_both_team"
    t.string "away_starter_last_game"
    t.string "away_starter_first_name"
    t.string "away_starter_handedness"
    t.string "home_starter_last_name"
    t.string "home_starter_first_name"
    t.string "home_starter_handedness"
    t.string "filtered_average_one"
    t.string "filtered_average_two"
    t.string "game_id"
    t.string "game_date"
    t.string "home_abbr"
    t.string "away_abbr"
    t.string "stadium"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "home_pitcher_name"
    t.string "home_pitcher_link"
    t.float "home_pitcher_ip"
    t.integer "home_pitcher_h"
    t.integer "home_pitcher_r"
    t.integer "home_pitcher_bb"
    t.string "away_pitcher_name"
    t.string "away_pitcher_link"
    t.float "away_pitcher_ip"
    t.integer "away_pitcher_h"
    t.integer "away_pitcher_r"
    t.integer "away_pitcher_bb"
    t.float "home_pitcher_game_first_ip"
    t.integer "home_pitcher_game_first_bb"
    t.integer "home_pitcher_game_first_h"
    t.integer "home_pitcher_game_first_r"
    t.float "home_pitcher_game_second_ip"
    t.integer "home_pitcher_game_second_bb"
    t.integer "home_pitcher_game_second_h"
    t.integer "home_pitcher_game_second_r"
    t.float "home_pitcher_game_opp_first_ip"
    t.integer "home_pitcher_game_opp_first_bb"
    t.integer "home_pitcher_game_opp_first_h"
    t.integer "home_pitcher_game_opp_first_r"
    t.float "home_pitcher_game_opp_second_ip"
    t.integer "home_pitcher_game_opp_second_bb"
    t.integer "home_pitcher_game_opp_second_h"
    t.integer "home_pitcher_game_opp_second_r"
    t.float "away_pitcher_game_first_ip"
    t.integer "away_pitcher_game_first_bb"
    t.integer "away_pitcher_game_first_h"
    t.integer "away_pitcher_game_first_r"
    t.float "away_pitcher_game_second_ip"
    t.integer "away_pitcher_game_second_bb"
    t.integer "away_pitcher_game_second_h"
    t.integer "away_pitcher_game_second_r"
    t.float "away_pitcher_game_opp_first_ip"
    t.integer "away_pitcher_game_opp_first_bb"
    t.integer "away_pitcher_game_opp_first_h"
    t.integer "away_pitcher_game_opp_first_r"
    t.float "away_pitcher_game_opp_second_ip"
    t.integer "away_pitcher_game_opp_second_bb"
    t.integer "away_pitcher_game_opp_second_h"
    t.integer "away_pitcher_game_opp_second_r"
  end

  create_table "scouts", force: :cascade do |t|
    t.bigint "player_scout_id"
    t.integer "row_index"
    t.string "season"
    t.integer "pitches"
    t.integer "batted_balls"
    t.integer "barrels"
    t.float "barrel"
    t.float "exit_velocity"
    t.float "launch_angle"
    t.string "xba"
    t.string "xslg"
    t.string "xwoba"
    t.string "woba"
    t.float "hard_hit"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["player_scout_id"], name: "index_scouts_on_player_scout_id"
  end

  create_table "seasons", force: :cascade do |t|
    t.integer "year"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "stadia", force: :cascade do |t|
    t.string "stadium"
    t.string "time"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "teams", force: :cascade do |t|
    t.string "name"
    t.string "espn_abbr"
    t.string "baseball_abbr"
    t.integer "fangraph_id"
    t.string "zipcode"
    t.integer "timezone"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "city"
    t.string "stadium"
    t.string "mlb_abbr"
  end

  create_table "totals", force: :cascade do |t|
    t.string "DATE"
    t.string "TIME"
    t.string "AWAY"
    t.string "HOME"
    t.integer "I1ASCORE"
    t.integer "I2ASCORE"
    t.integer "I3ASCORE"
    t.integer "I4ASCORE"
    t.integer "I5ASCORE"
    t.integer "I6ASCORE"
    t.integer "I7ASCORE"
    t.integer "I8ASCORE"
    t.integer "I9ASCORE"
    t.integer "I0ASCORE"
    t.integer "I1HSCORE"
    t.integer "I2HSCORE"
    t.integer "I3HSCORE"
    t.integer "I4HSCORE"
    t.integer "I5HSCORE"
    t.integer "I6HSCORE"
    t.integer "I7HSCORE"
    t.integer "I8HSCORE"
    t.integer "I9HSCORE"
    t.integer "I0HSCORE"
    t.integer "AWAYSCORE"
    t.integer "HOMESCORE"
    t.integer "EXTRAINN"
    t.integer "NEUTRAL"
    t.integer "GAMENUM"
    t.integer "DAY"
    t.integer "GRASS"
    t.float "TOTAL"
    t.string "TOTALOU"
    t.float "TOTALODD"
    t.float "I5ML"
    t.string "I5FAV"
    t.float "I5TOT"
    t.string "I5TOTOU"
    t.float "I5TOTODD"
    t.float "I5RL"
    t.string "I5RLFAV"
    t.float "I5RLODD"
    t.integer "PLAYOFFS"
    t.string "DESC"
    t.string "GAMETYP"
    t.string "HSTARTF"
    t.string "HSTARTL"
    t.string "HHAND"
    t.string "ASTARTF"
    t.string "ASTARTL"
    t.string "AHAND"
    t.float "HSIP"
    t.integer "HSHITS"
    t.integer "HSRUNS"
    t.integer "HSERUNS"
    t.integer "HS2B"
    t.integer "HS3B"
    t.integer "HSHR"
    t.integer "HSWK"
    t.integer "HSK"
    t.integer "HSHB"
    t.integer "HSPC"
    t.integer "HSSTRIKES"
    t.integer "HSBF"
    t.integer "HSGB"
    t.integer "HSFB"
    t.integer "HSSF"
    t.integer "HSSH"
    t.integer "HSDP"
    t.integer "HSIBB"
    t.integer "HSSB"
    t.integer "HSCS"
    t.integer "HSWP"
    t.integer "HSPB"
    t.integer "HSBALK"
    t.string "HSRES"
    t.string "HSNOTEFLAG"
    t.string "HSNOTES"
    t.float "ASIP"
    t.integer "ASHITS"
    t.integer "ASRUNS"
    t.integer "ASERUNS"
    t.integer "AS2B"
    t.integer "AS3B"
    t.integer "ASHR"
    t.integer "ASWK"
    t.integer "ASK"
    t.integer "ASHB"
    t.integer "ASPC"
    t.integer "ASSTRIKES"
    t.integer "ASBF"
    t.integer "ASGB"
    t.integer "ASFB"
    t.integer "ASSF"
    t.integer "ASSH"
    t.integer "ASDP"
    t.integer "ASIBB"
    t.integer "ASSB"
    t.integer "ASCS"
    t.integer "ASWP"
    t.integer "ASPB"
    t.integer "ASBALK"
    t.string "ASRES"
    t.string "ASNOTEFLAG"
    t.string "ASNOTES"
    t.float "HLRIP"
    t.integer "HLRHITS"
    t.integer "HLRRUNS"
    t.integer "HLRERUNS"
    t.integer "HLR2B"
    t.integer "HLR3B"
    t.integer "HLRHR"
    t.integer "HLRWK"
    t.integer "HLRK"
    t.integer "HLRHB"
    t.integer "HLRPC"
    t.integer "HLRSTRIKES"
    t.integer "HLRBF"
    t.integer "HLRGB"
    t.integer "HLRSF"
    t.integer "HLRSH"
    t.integer "HLRDP"
    t.integer "HLRIBB"
    t.integer "HLRSB"
    t.integer "HLRCS"
    t.integer "HLRWP"
    t.integer "HLRPB"
    t.integer "HLRBALK"
    t.string "HLRRES"
    t.float "ALRIP"
    t.integer "ALRHITS"
    t.integer "ALRRUNS"
    t.integer "ALRERUNS"
    t.integer "ALR2B"
    t.integer "ALR3B"
    t.integer "ALRHR"
    t.integer "ALRWK"
    t.integer "ALRK"
    t.integer "ALRHB"
    t.integer "ALRPC"
    t.integer "ALRSTRIKES"
    t.integer "ALRBF"
    t.integer "ALRGB"
    t.integer "ALRSF"
    t.integer "ALRSH"
    t.integer "ALRDP"
    t.integer "ALRIBB"
    t.integer "ALRSB"
    t.integer "ALRCS"
    t.integer "ALRWP"
    t.integer "ALRPB"
    t.integer "ALRBALK"
    t.string "ALRRES"
    t.float "HSRIP"
    t.integer "HSRHITS"
    t.integer "HSRRUNS"
    t.integer "HSRERUNS"
    t.integer "HSR2B"
    t.integer "HSR3B"
    t.integer "HSRHR"
    t.integer "HSRWK"
    t.integer "HSRK"
    t.integer "HSRHB"
    t.integer "HSRPC"
    t.integer "HSRSTRIKES"
    t.integer "HSRBF"
    t.integer "HSRGB"
    t.integer "HSRSF"
    t.integer "HSRSH"
    t.integer "HSRDP"
    t.integer "HSRIBB"
    t.integer "HSRSB"
    t.integer "HSRCS"
    t.integer "HSRWP"
    t.integer "HSRPB"
    t.integer "HSRBALK"
    t.string "HSRRES"
    t.float "ASRIP"
    t.integer "ASRHITS"
    t.integer "ASRRUNS"
    t.integer "ASRERUNS"
    t.integer "ASR2B"
    t.integer "ASR3B"
    t.integer "ASRHR"
    t.integer "ASRWK"
    t.integer "ASRK"
    t.integer "ASRHB"
    t.integer "ASRPC"
    t.integer "ASRSTRIKES"
    t.integer "ASRBF"
    t.integer "ASRGB"
    t.integer "ASRSF"
    t.integer "ASRSH"
    t.integer "ASRDP"
    t.integer "ASRIBB"
    t.integer "ASRSB"
    t.integer "ASRCS"
    t.integer "ASRWP"
    t.integer "ASRPB"
    t.integer "ASRBALK"
    t.string "ASRRES"
    t.integer "HAB"
    t.integer "AAB"
    t.integer "HLOB"
    t.integer "ALOB"
    t.integer "HERRORS"
    t.integer "AERRORS"
    t.string "UMPIREF"
    t.string "UMPIREL"
    t.integer "RT"
    t.integer "RC"
    t.integer "CTR"
    t.integer "LC"
    t.integer "LT"
    t.integer "HWIN"
    t.integer "HLOSS"
    t.integer "AWIN"
    t.integer "ALOSS"
    t.integer "TEMP"
    t.string "COND"
    t.integer "WIND"
    t.string "DIR"
    t.integer "HUMIDITY"
    t.float "BAROMETER"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string "username", default: ""
    t.string "password_digest", default: ""
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "weather_firsts", force: :cascade do |t|
    t.string "Date"
    t.string "Time"
    t.string "Away_Team"
    t.string "Home_Team"
    t.integer "Away_Money_Line"
    t.integer "Home_Money_Line"
    t.string "D2"
    t.string "Away_Total"
    t.float "TEMP"
    t.float "DP"
    t.integer "HUMID"
    t.float "BARo"
    t.string "Direction"
    t.float "Speed"
    t.float "Average"
    t.integer "Total_Hits"
    t.integer "Total_Walks"
    t.integer "Total_Walks_Hits"
    t.integer "Total_Bases"
    t.integer "Away_Inning_1"
    t.integer "h9"
    t.integer "h8"
    t.integer "h7"
    t.integer "h6"
    t.integer "h5"
    t.string "h4"
    t.string "h3"
    t.string "h2"
    t.string "h1"
    t.string "Home_Inning_1"
    t.integer "a9"
    t.integer "a8"
    t.integer "a7"
    t.integer "a6"
    t.integer "a5"
    t.string "a4"
    t.string "A3"
    t.string "A2"
    t.string "A1"
    t.string "A0"
    t.integer "home_runs"
    t.integer "stolen_bases"
    t.string "Away_Starter_First_Name"
    t.string "Away_Starter_Last_Name"
    t.string "Away_Starter_Handedness"
    t.string "Home_Starter_First_Name"
    t.string "Home_Starter_Last_Name"
    t.string "Home_Starter_Handedness"
    t.float "LD_PA"
    t.float "GB_PA"
    t.float "FB_PA"
    t.float "SO_PA"
    t.float "LD_BABIP"
    t.float "GB_BABIP"
    t.float "FB_BABIP"
    t.integer "game_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "hits1"
    t.integer "home_runs1"
    t.integer "hits2"
    t.integer "home_runs2"
    t.integer "hits3"
    t.integer "home_runs3"
    t.integer "hits4"
    t.integer "home_runs4"
    t.integer "hits5"
    t.integer "home_runs5"
    t.integer "hits6"
    t.integer "home_runs6"
    t.integer "hits7"
    t.integer "home_runs7"
    t.integer "hits8"
    t.integer "home_runs8"
    t.integer "hits9"
    t.integer "home_runs9"
    t.integer "hits10"
    t.integer "home_runs10"
  end

  create_table "weather_seconds", force: :cascade do |t|
    t.integer "day"
    t.string "month"
    t.integer "year"
    t.string "time"
    t.string "away_team"
    t.string "home_team"
    t.integer "away_ml"
    t.integer "home_ml"
    t.string "away_total"
    t.string "home_total"
    t.float "TEMP"
    t.float "DP"
    t.string "humid"
    t.float "BARO"
    t.string "wind"
    t.string "speed"
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "h1"
    t.string "h2"
    t.string "h3"
    t.string "h4"
    t.integer "total_home_runs_both_team"
    t.integer "total_hits_both_team"
    t.string "away_starter_last_game"
    t.string "away_starter_first_name"
    t.string "away_starter_handedness"
    t.float "away_pitcher_game_first_blue"
    t.float "away_pitcher_game_opp_first_blue"
    t.float "away_pitcher_game_second_blue"
    t.float "away_pitcher_game_opp_second_blue"
    t.string "home_starter_last_name"
    t.string "home_starter_first_name"
    t.string "home_starter_handedness"
    t.float "home_pitcher_game_first_blue"
    t.float "home_pitcher_game_opp_first_blue"
    t.float "home_pitcher_game_second_blue"
    t.float "home_pitcher_game_opp_second_blue"
    t.integer "game_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "hits1"
    t.integer "home_runs1"
    t.integer "hits2"
    t.integer "home_runs2"
    t.integer "hits3"
    t.integer "home_runs3"
    t.integer "hits4"
    t.integer "home_runs4"
    t.integer "hits5"
    t.integer "home_runs5"
    t.integer "hits6"
    t.integer "home_runs6"
    t.integer "hits7"
    t.integer "home_runs7"
    t.integer "hits8"
    t.integer "home_runs8"
    t.integer "hits9"
    t.integer "home_runs9"
    t.integer "hits10"
    t.integer "home_runs10"
  end

  create_table "weathers", force: :cascade do |t|
    t.bigint "game_id"
    t.string "station"
    t.integer "hour"
    t.string "temp"
    t.string "dp"
    t.string "hum"
    t.string "pressure"
    t.string "wind_dir"
    t.string "wind_speed"
    t.string "precip"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "feel"
    t.index ["game_id"], name: "index_weathers_on_game_id"
  end

  create_table "weathersources", force: :cascade do |t|
    t.bigint "game_id"
    t.string "date"
    t.integer "offset"
    t.integer "table_number"
    t.integer "block_number"
    t.integer "row_number"
    t.string "caption"
    t.string "temp"
    t.string "dew"
    t.string "humid"
    t.string "pressure"
    t.string "wind"
    t.float "all_stadium_total_average_one"
    t.float "all_stadium_total_average_two"
    t.float "all_stadium_total_hits_average"
    t.float "all_stadium_home_runs_average"
    t.integer "all_stadium_total_count"
    t.float "all_stadium_min_total_average"
    t.integer "all_stadium_min_total_count"
    t.float "all_stadium_total_lines_average"
    t.float "only_total_average_one"
    t.float "only_total_average_two"
    t.float "only_total_hits_average"
    t.float "only_home_runs_average"
    t.integer "only_total_count"
    t.float "only_min_total_average"
    t.integer "only_min_total_count"
    t.float "only_total_lines_average"
    t.float "only_wind_total_average_one"
    t.float "only_wind_total_average_two"
    t.float "only_wind_total_hits_average"
    t.float "only_wind_home_runs_average"
    t.integer "only_wind_total_count"
    t.float "only_wind_min_total_average"
    t.integer "only_wind_min_total_count"
    t.float "only_wind_total_lines_average"
    t.float "except_total_average_one"
    t.float "except_total_average_two"
    t.float "except_total_hits_average"
    t.float "except_home_runs_average"
    t.integer "except_total_count"
    t.float "except_min_total_average"
    t.integer "except_min_total_count"
    t.float "except_total_lines_average"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["game_id"], name: "index_weathersources_on_game_id"
  end

  create_table "workbooks", force: :cascade do |t|
    t.string "Home_Team"
    t.float "TEMP"
    t.float "DP"
    t.float "HUMID"
    t.float "BARo"
    t.string "M"
    t.float "N"
    t.float "R"
    t.float "Total_Hits"
    t.float "Total_Walks"
    t.float "home_runs"
    t.string "table"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "Date"
    t.string "Time"
    t.string "Away_Team"
    t.integer "Away_Money_Line"
    t.integer "Home_Money_Line"
    t.string "Away_Total"
    t.string "Home_Total"
    t.float "O"
    t.float "P"
    t.float "Q"
    t.integer "Total_Walks_Hits"
    t.integer "Total_Bases"
    t.integer "Away_Inning_1"
    t.integer "h9"
    t.integer "h8"
    t.integer "h7"
    t.integer "h6"
    t.integer "h5"
    t.integer "h4"
    t.integer "h3"
    t.integer "h2"
    t.integer "h1"
    t.string "Home_Inning_1"
    t.integer "a9"
    t.integer "a8"
    t.integer "a7"
    t.integer "a6"
    t.integer "a5"
    t.integer "a4"
    t.integer "A3"
    t.integer "A2"
    t.integer "A1"
    t.string "AQ"
    t.integer "stolen_bases"
    t.string "Away_Starter_Last_Name"
    t.string "Away_Starter_Handedness"
    t.string "Home_Starter_First_Name"
    t.string "Home_Starter_Last_Name"
    t.string "Home_Starter_Handedness"
    t.string "LD_PA"
    t.float "GB_PA"
    t.float "FB_PA"
    t.float "SO_PA"
    t.float "LD_BABIP"
    t.float "GB_BABIP"
    t.float "FB_BABIP"
    t.float "BF"
    t.float "total_line"
  end

end
