class CreateTotals < ActiveRecord::Migration[5.1]
  def change
    create_table :totals do |t|
      t.string :DATE
      t.string :TIME
      t.string :AWAY
      t.string :HOME
      t.integer :I1ASCORE
      t.integer :I2ASCORE
      t.integer :I3ASCORE
      t.integer :I4ASCORE
      t.integer :I5ASCORE
      t.integer :I6ASCORE
      t.integer :I7ASCORE
      t.integer :I8ASCORE
      t.integer :I9ASCORE
      t.integer :I0ASCORE
      t.integer :I1HSCORE
      t.integer :I2HSCORE
      t.integer :I3HSCORE
      t.integer :I4HSCORE
      t.integer :I5HSCORE
      t.integer :I6HSCORE
      t.integer :I7HSCORE
      t.integer :I8HSCORE
      t.integer :I9HSCORE
      t.integer :I0HSCORE
      t.integer :AWAYSCORE
      t.integer :HOMESCORE
      t.integer :EXTRAINN
      t.integer :NEUTRAL
      t.integer :GAMENUM
      t.integer :DAY
      t.integer :GRASS
      t.float :TOTAL
      t.string :TOTALOU
      t.float :TOTALODD
      t.float :I5ML
      t.string :I5FAV
      t.float :I5TOT
      t.string :I5TOTOU
      t.float :I5TOTODD
      t.float :I5RL
      t.string :I5RLFAV
      t.float :I5RLODD
      t.integer :PLAYOFFS
      t.string :DESC
      t.string :GAMETYP
      t.string :HSTARTF
      t.string :HSTARTL
      t.string :HHAND
      t.string :ASTARTF
      t.string :ASTARTL
      t.string :AHAND
      t.float :HSIP
      t.integer :HSHITS
      t.integer :HSRUNS
      t.integer :HSERUNS
      t.integer :HS2B
      t.integer :HS3B
      t.integer :HSHR
      t.integer :HSWK
      t.integer :HSK
      t.integer :HSHB
      t.integer :HSPC
      t.integer :HSSTRIKES
      t.integer :HSBF
      t.integer :HSGB
      t.integer :HSFB
      t.integer :HSSF
      t.integer :HSSH
      t.integer :HSDP
      t.integer :HSIBB
      t.integer :HSSB
      t.integer :HSCS
      t.integer :HSWP
      t.integer :HSPB
      t.integer :HSBALK
      t.string :HSRES
      t.string :HSNOTEFLAG
      t.string :HSNOTES
      t.float :ASIP
      t.integer :ASHITS
      t.integer :ASRUNS
      t.integer :ASERUNS
      t.integer :AS2B
      t.integer :AS3B
      t.integer :ASHR
      t.integer :ASWK
      t.integer :ASK
      t.integer :ASHB
      t.integer :ASPC
      t.integer :ASSTRIKES
      t.integer :ASBF
      t.integer :ASGB
      t.integer :ASFB
      t.integer :ASSF
      t.integer :ASSH
      t.integer :ASDP
      t.integer :ASIBB
      t.integer :ASSB
      t.integer :ASCS
      t.integer :ASWP
      t.integer :ASPB
      t.integer :ASBALK
      t.string :ASRES
      t.string :ASNOTEFLAG
      t.string :ASNOTES
      t.float :HLRIP
      t.integer :HLRHITS
      t.integer :HLRRUNS
      t.integer :HLRERUNS
      t.integer :HLR2B
      t.integer :HLR3B
      t.integer :HLRHR
      t.integer :HLRWK
      t.integer :HLRK
      t.integer :HLRHB
      t.integer :HLRPC
      t.integer :HLRSTRIKES
      t.integer :HLRBF
      t.integer :HLRGB
      t.integer :HLRSF
      t.integer :HLRSH
      t.integer :HLRDP
      t.integer :HLRIBB
      t.integer :HLRSB
      t.integer :HLRCS
      t.integer :HLRWP
      t.integer :HLRPB
      t.integer :HLRBALK
      t.string :HLRRES
      t.float :ALRIP
      t.integer :ALRHITS
      t.integer :ALRRUNS
      t.integer :ALRERUNS
      t.integer :ALR2B
      t.integer :ALR3B
      t.integer :ALRHR
      t.integer :ALRWK
      t.integer :ALRK
      t.integer :ALRHB
      t.integer :ALRPC
      t.integer :ALRSTRIKES
      t.integer :ALRBF
      t.integer :ALRGB
      t.integer :ALRSF
      t.integer :ALRSH
      t.integer :ALRDP
      t.integer :ALRIBB
      t.integer :ALRSB
      t.integer :ALRCS
      t.integer :ALRWP
      t.integer :ALRPB
      t.integer :ALRBALK
      t.string :ALRRES
      t.float :HSRIP
      t.integer :HSRHITS
      t.integer :HSRRUNS
      t.integer :HSRERUNS
      t.integer :HSR2B
      t.integer :HSR3B
      t.integer :HSRHR
      t.integer :HSRWK
      t.integer :HSRK
      t.integer :HSRHB
      t.integer :HSRPC
      t.integer :HSRSTRIKES
      t.integer :HSRBF
      t.integer :HSRGB
      t.integer :HSRSF
      t.integer :HSRSH
      t.integer :HSRDP
      t.integer :HSRIBB
      t.integer :HSRSB
      t.integer :HSRCS
      t.integer :HSRWP
      t.integer :HSRPB
      t.integer :HSRBALK
      t.string :HSRRES
      t.float :ASRIP
      t.integer :ASRHITS
      t.integer :ASRRUNS
      t.integer :ASRERUNS
      t.integer :ASR2B
      t.integer :ASR3B
      t.integer :ASRHR
      t.integer :ASRWK
      t.integer :ASRK
      t.integer :ASRHB
      t.integer :ASRPC
      t.integer :ASRSTRIKES
      t.integer :ASRBF
      t.integer :ASRGB
      t.integer :ASRSF
      t.integer :ASRSH
      t.integer :ASRDP
      t.integer :ASRIBB
      t.integer :ASRSB
      t.integer :ASRCS
      t.integer :ASRWP
      t.integer :ASRPB
      t.integer :ASRBALK
      t.string :ASRRES
      t.integer :HAB
      t.integer :AAB
      t.integer :HLOB
      t.integer :ALOB
      t.integer :HERRORS
      t.integer :AERRORS
      t.string :UMPIREF
      t.string :UMPIREL
      t.integer :RT
      t.integer :RC
      t.integer :CTR
      t.integer :LC
      t.integer :LT
      t.integer :HWIN
      t.integer :HLOSS
      t.integer :AWIN
      t.integer :ALOSS
      t.integer :TEMP
      t.string :COND
      t.integer :WIND
      t.string :DIR
      t.integer :HUMIDITY
      t.float :BAROMETER
      t.timestamps
    end
  end
end
