class CreateNewworkbooks < ActiveRecord::Migration[5.1]
  def change
    create_table :newworkbooks do |t|
      t.string :Date
      t.string :Time
      t.string :Away_Team
      t.string :Home_Team
      t.integer :Away_Money_Line
      t.integer :Home_Money_Line
      t.string :Away_Total
      t.string :Home_Total
      t.integer :TEMP
      t.integer :DP
      t.integer :HUMID
      t.float :BARo
      t.string :Direction
      t.float :Speed
      t.float :O
      t.float :P
      t.float :Q
      t.float :R
      t.integer :S
      t.integer :Total_Walks
      t.integer :Total_Walks_Hits
      t.integer :Total_Bases
      t.integer :W
      t.integer :h9
      t.integer :h8
      t.integer :h7
      t.integer :h6
      t.integer :h5
      t.integer :h4
      t.integer :h3
      t.integer :h2
      t.integer :h1
      t.string :Home_Inning_1
      t.integer :a9
      t.integer :a8
      t.integer :a7
      t.integer :a6
      t.integer :a5
      t.integer :a4
      t.integer :A3
      t.integer :A2
      t.integer :A1
      t.string :AQ
      t.integer :AR
      t.integer :stolen_bases
      t.string :Away_Starter_First_Name
      t.string :Away_Starter_Last_Name
      t.string :Away_Starter_Handedness
      t.string :Home_Starter_First_Name
      t.string :Home_Starter_Last_Name
      t.string :Home_Starter_Handedness
      t.float :LD_PA
      t.float :GB_PA
      t.float :FB_PA
      t.float :SO_PA
      t.float :LD_BABIP
      t.float :GB_BABIP
      t.float :FB_BABIP
      t.integer :hits1
      t.integer :hits2
      t.integer :hits3
      t.integer :hits4
      t.integer :hits5
      t.integer :hits6
      t.integer :hits7
      t.integer :hits8
      t.integer :hits9
      t.integer :home_runs1
      t.integer :home_runs2
      t.integer :home_runs3
      t.integer :home_runs4
      t.integer :home_runs5
      t.integer :home_runs6
      t.integer :home_runs7
      t.integer :home_runs8
      t.integer :home_runs9
      t.integer :hits_sum
      t.float :t_HITS
      t.integer :home_runs_sum
      t.float :t_HRS
      t.timestamps
    end
  end
end
